# Streamlit Cloud에서 사용할 환경 변수 설정
[mysql]
host = "your_mysql_host"
port = "your_mysql_port"
user = "your_mysql_user"
password = "your_mysql_password"
database = "your_mysql_database"
[openai]
api_key = "your_openai_api_key"
